name: autoimmune_ml
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  - pip

  # Core Libraries
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.14.1
  - scikit-learn=1.6.0
  - matplotlib=3.9.3
  - seaborn=0.13.2
  - pytorch-lightning=2.4.0
  - tensorflow=2.17.0
  - torch=2.5.1
  - optuna=4.1.0

  # Image and Spatial Libraries
  - scikit-image=0.24.0
  - opencv=4.10.0
  - imageio=2.36.1
  - ome-zarr=0.9.0
  - spatialdata=0.2.6
  - shapely=2.0.6
  - zarr=2.18.3

  # Bioinformatics
  - biopython=1.84
  - pysam=0.22.1
  - scanpy=1.10.4

  # Utilities and Supporting Libraries
  - h5py=3.12.1
  - pillow=11.0.0
  - pyparsing=3.2.0
  - tqdm=4.67.1
  - pyzmq=26.2.0
  - yaml=0.2.5
  - pyyaml=6.0.2
  - zstandard=0.23.0
  - lz4-c=1.9.4
  - zlib-ng=2.2.2
  - libtiff=4.7.0
  - tifffile=2024.9.20

  # Pip-installed Libraries
  - pip:
      - crunch-cli==5.7.3
      - opencv-python==4.10.0.84
      - openslide-python==1.4.1
      - pydantic==2.10.3
